baseURL = "https://gokarna-hugo.netlify.app"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"
theme = "gokarna"
title = "Asafe Belo"

[params]
  avatarAltText = "asafe"
  avatarSize = "size-m"
  avatarURL = "/images/asafe.jpg"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  description = "Tecnologia, Música e Eu"
  footer = "By Asafe :)"
  metaKeywords = ["blog", "gokarna", "hugo", "asafe belo", "asafe", "cybersecurity"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/asafebelo/"},
    {name = "github", url = "https://github.com/asafebelo"},
    {name = "shield", url = "https://app.letsdefend.io/user/asafebelo"},
    {name = "email", url = "mailto:asafebelo@proton.me"},
    {name = "youtube", url = "https://www.youtube.com/@beloasafe"},
    {name = "soundcloud", url = "https://soundcloud.com/asafebelo"},
    {name = "instagram", url = "https://www.instagram.com/asafebelo"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog do Asafe"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true